export const MOCK_EQUIPMENT = [
  {
    id: 'EQP-001',
    name: 'Desfibrilador',
    model: 'HeartStart XL+',
    manufacturer: 'Philips',
    serial: 'DE451A2Z3',
    location: 'Sala de Emergencias',
    status: 'Activo',
    installationDate: '2023-01-15',
    invima: 'INV-2019-12345',
    risk: 'IIb',
    imageUrl: 'https://picsum.photos/seed/EQP-001/600/400',
    imageZoom: 1,
    sede: 'Principal',
    accessories: [
      { name: 'Paletas externas', observation: 'Adulto/Pediátrico' },
      { name: 'Batería recargable', observation: 'Modelo M3538A' },
    ],
    predominantTechnologies: ['Electrónica'],
    technicalParameters: {
      voltage: '100-240 VCA',
      current: '1.7-0.8 A',
      frequency: '50/60 Hz',
      power: '150 W'
    },
    supplies: [{ name: 'Electricidad', value: '110V' }],
    otherCharacteristics: [{ name: 'Peso', value: '7 kg' }],
  },
  {
    id: 'EQP-002',
    name: 'Ventilador',
    model: 'Puritan Bennett 980',
    manufacturer: 'Medtronic',
    serial: 'PB980B3Y4',
    location: 'UCI',
    status: 'Activo',
    installationDate: '2022-06-20',
    invima: 'INV-2020-67890',
    risk: 'IIb',
    imageUrl: 'https://picsum.photos/seed/EQP-002/600/400',
    imageZoom: 1,
    sede: 'Secundaria',
    accessories: [{ name: 'Circuito de paciente', observation: 'Desechable' }],
    predominantTechnologies: ['Neumática', 'Electrónica'],
    technicalParameters: {
      pressure: '2.8-6.2 bar',
      flow: '200 L/min'
    },
    supplies: [
      { name: 'Electricidad', value: '220V' },
      { name: 'Oxígeno', value: '50 psi' },
      { name: 'Aire', value: '50 psi' }
    ],
    otherCharacteristics: [],
  },
  {
    id: 'EQP-003',
    name: 'Máquina de Ultrasonido',
    model: 'LOGIQ E10',
    manufacturer: 'GE Healthcare',
    serial: 'LE10C4X5',
    location: 'Radiología',
    status: 'Fuera de Servicio',
    installationDate: '2021-09-01',
    invima: 'INV-2018-54321',
    risk: 'IIa',
    imageUrl: 'https://picsum.photos/seed/EQP-003/600/400',
    imageZoom: 1,
    sede: 'Terciaria',
    accessories: [{ name: 'Transductor convexo', observation: '' }],
    predominantTechnologies: ['Software', 'Electrónica'],
    technicalParameters: {},
    supplies: [{ name: 'Electricidad', value: '110V' }],
    otherCharacteristics: [],
  },
  {
    id: 'EQP-004',
    name: 'Máquina de ECG',
    model: 'MAC 5500 HD',
    manufacturer: 'GE Healthcare',
    serial: 'MAC55D5W6',
    location: 'Cardiología',
    status: 'Activo',
    installationDate: '2022-02-10',
    invima: 'INV-2017-98765',
    risk: 'IIa',
    imageUrl: 'https://picsum.photos/seed/EQP-004/600/400',
    imageZoom: 1,
    sede: 'Principal',
    accessories: [],
    predominantTechnologies: ['Electrónica'],
    technicalParameters: {
      voltage: '100-240 VCA',
      frequency: '50/60 Hz'
    },
    supplies: [{ name: 'Electricidad', value: 'Batería' }],
    otherCharacteristics: [],
  },
  {
    id: 'EQP-005',
    name: 'Bomba de Infusión',
    model: 'Alaris PC 8015',
    manufacturer: 'BD',
    serial: 'AP801E6V7',
    location: 'Pabellón General',
    status: 'Dado de Baja',
    installationDate: '2020-11-05',
    invima: 'INV-2019-24680',
    risk: 'IIa',
    imageUrl: 'https://picsum.photos/seed/EQP-005/600/400',
    imageZoom: 1,
    sede: 'Secundaria',
    accessories: [],
    predominantTechnologies: ['Mecánica', 'Electrónica'],
    technicalParameters: {},
    supplies: [{ name: 'Electricidad', value: 'Batería' }],
    otherCharacteristics: [],
  },
  {
    id: 'EQP-006',
    name: 'Máquina de Anestesia',
    model: 'Aisys CS2',
    manufacturer: 'GE Healthcare',
    serial: 'AC2F7U8',
    location: 'Quirófano 1',
    status: 'Activo',
    installationDate: '2023-03-25',
    invima: 'INV-2021-13579',
    risk: 'IIb',
    imageUrl: 'https://picsum.photos/seed/EQP-006/600/400',
    imageZoom: 1,
    sede: 'Terciaria',
    accessories: [],
    predominantTechnologies: ['Neumática', 'Electrónica'],
    technicalParameters: {},
    supplies: [
        { name: 'Electricidad', value: '220V' },
        { name: 'Oxígeno', value: '50 psi' },
        { name: 'Vacío', value: '-20 inHg' }
    ],
    otherCharacteristics: [],
  },
  {
    id: 'EQP-007',
    name: 'Monitor de Signos Vitales',
    model: 'IntelliVue MX700',
    manufacturer: 'Philips',
    serial: 'MX700G7H8',
    location: 'UCI 2',
    status: 'Activo',
    installationDate: '2023-08-15',
    invima: 'INV-2022-11223',
    risk: 'IIb',
    imageUrl: 'https://picsum.photos/seed/EQP-007/600/400',
    imageZoom: 1,
    sede: 'Principal',
    accessories: [],
    predominantTechnologies: ['Electrónica', 'Software'],
    technicalParameters: {},
    supplies: [{ name: 'Electricidad', value: '110V' }],
    otherCharacteristics: [],
  },
  {
    id: 'EQP-008',
    name: 'Electrocardiógrafo Portátil',
    model: 'PageWriter TC20',
    manufacturer: 'Philips',
    serial: 'PWTC2H8J9',
    location: 'Ambulancia 1',
    status: 'Activo',
    installationDate: '2023-09-01',
    invima: 'INV-2021-33445',
    risk: 'IIa',
    imageUrl: 'https://picsum.photos/seed/EQP-008/600/400',
    imageZoom: 1,
    sede: 'Secundaria',
    accessories: [],
    predominantTechnologies: ['Electrónica'],
    technicalParameters: {},
    supplies: [{ name: 'Electricidad', value: 'Batería' }],
    otherCharacteristics: [],
  },
  {
    id: 'EQP-009',
    name: 'Bisturí Eléctrico',
    model: 'Valleylab FT10',
    manufacturer: 'Medtronic',
    serial: 'VLFT10J9K0',
    location: 'Quirófano 2',
    status: 'Activo',
    installationDate: '2022-07-18',
    invima: 'INV-2020-55667',
    risk: 'IIb',
    imageUrl: 'https://picsum.photos/seed/EQP-009/600/400',
    imageZoom: 1,
    sede: 'Principal',
    accessories: [],
    predominantTechnologies: ['Eléctrica'],
    technicalParameters: {},
    supplies: [{ name: 'Electricidad', value: '110V' }],
    otherCharacteristics: [],
  },
  {
    id: 'EQP-010',
    name: 'Incubadora Neonatal',
    model: 'Giraffe OmniBed',
    manufacturer: 'GE Healthcare',
    serial: 'GOK0L1M2',
    location: 'Neonatología',
    status: 'Fuera de Servicio',
    installationDate: '2021-12-01',
    invima: 'INV-2019-77889',
    risk: 'IIb',
    imageUrl: 'https://picsum.photos/seed/EQP-010/600/400',
    imageZoom: 1,
    sede: 'Terciaria',
    accessories: [],
    predominantTechnologies: ['Eléctrica'],
    technicalParameters: {},
    supplies: [{ name: 'Electricidad', value: '110V' }],
    otherCharacteristics: [{name: 'Temperatura', value: '37°C'}],
  },
  {
    id: 'EQP-011',
    name: 'Lámpara Quirúrgica',
    model: 'Maquet PowerLED II',
    manufacturer: 'Getinge',
    serial: 'MPLED2M2N3',
    location: 'Quirófano 3',
    status: 'Activo',
    installationDate: '2023-05-20',
    invima: 'INV-2022-99001',
    risk: 'I',
    imageUrl: 'https://picsum.photos/seed/EQP-011/600/400',
    imageZoom: 1,
    sede: 'Principal',
    accessories: [],
    predominantTechnologies: ['Eléctrica'],
    technicalParameters: {},
    supplies: [{ name: 'Electricidad', value: '110V' }],
    otherCharacteristics: [],
  },
  {
    id: 'EQP-012',
    name: 'Cama Hospitalaria Eléctrica',
    model: 'Centrella Smart+ Bed',
    manufacturer: 'Hill-Rom',
    serial: 'CENSMN3P4',
    location: 'Piso 3, Hab 301',
    status: 'Activo',
    installationDate: '2022-10-10',
    invima: 'INV-2020-11223',
    risk: 'I',
    imageUrl: 'https://picsum.photos/seed/EQP-012/600/400',
    imageZoom: 1,
    sede: 'Secundaria',
    accessories: [],
    predominantTechnologies: ['Eléctrica', 'Mecánica'],
    technicalParameters: {},
    supplies: [{ name: 'Electricidad', value: '110V' }],
    otherCharacteristics: [],
  },
  {
    id: 'EQP-013',
    name: 'Tomógrafo Computarizado',
    model: 'Somatom go.Up',
    manufacturer: 'Siemens Healthineers',
    serial: 'SGOUP4Q5R6',
    location: 'Imagenología',
    status: 'Activo',
    installationDate: '2020-04-15',
    invima: 'INV-2018-33445',
    risk: 'IIb',
    imageUrl: 'https://picsum.photos/seed/EQP-013/600/400',
    imageZoom: 1,
    sede: 'Terciaria',
    accessories: [],
    predominantTechnologies: ['Software', 'Eléctrica'],
    technicalParameters: {},
    supplies: [
        { name: 'Electricidad', value: '480V' },
        { name: 'Refrigerante', value: 'Agua' }
    ],
    otherCharacteristics: [],
  },
  {
    id: 'EQP-014',
    name: 'Centrífuga de Laboratorio',
    model: 'Allegra X-15R',
    manufacturer: 'Beckman Coulter',
    serial: 'AX15R5S6T7',
    location: 'Laboratorio Clínico',
    status: 'Activo',
    installationDate: '2022-01-30',
    invima: 'INV-2019-55667',
    risk: 'I',
    imageUrl: 'https://picsum.photos/seed/EQP-014/600/400',
    imageZoom: 1,
    sede: 'Principal',
    accessories: [],
    predominantTechnologies: ['Mecánica'],
    technicalParameters: {},
    supplies: [{ name: 'Electricidad', value: '220V' }],
    otherCharacteristics: [{ name: 'Velocidad', value: '10,200 RPM'}],
  },
  {
    id: 'EQP-015',
    name: 'Autoclave de Vapor',
    model: '44B',
    manufacturer: 'Tuttnauer',
    serial: 'T44B6T7U8',
    location: 'Central de Esterilización',
    status: 'Activo',
    installationDate: '2021-08-22',
    invima: 'INV-2020-77889',
    risk: 'IIa',
    imageUrl: 'https://picsum.photos/seed/EQP-015/600/400',
    imageZoom: 1,
    sede: 'Secundaria',
    accessories: [],
    predominantTechnologies: ['Hidráulica', 'Eléctrica'],
    technicalParameters: {},
    supplies: [
        { name: 'Electricidad', value: '220V' },
        { name: 'Agua', value: 'Desionizada' },
        { name: 'Vapor', value: 'Planta' }
    ],
    otherCharacteristics: [{ name: 'Temperatura', value: '134°C'}],
  },
  {
    id: 'EQP-016',
    name: 'Monitor Fetal',
    model: 'Avalon FM30',
    manufacturer: 'Philips',
    serial: 'AVFM30U8V9',
    location: 'Ginecología y Obstetricia',
    status: 'Fuera de Servicio',
    installationDate: '2019-07-12',
    invima: 'INV-2018-99001',
    risk: 'IIa',
    imageUrl: 'https://picsum.photos/seed/EQP-016/600/400',
    imageZoom: 1,
    sede: 'Terciaria',
    accessories: [],
    predominantTechnologies: ['Electrónica'],
    technicalParameters: {},
    supplies: [{ name: 'Electricidad', value: 'Batería' }],
    otherCharacteristics: [],
  },
  {
    id: 'EQP-017',
    name: 'Equipo de Rayos X Móvil',
    model: 'Mobilett Elara Max',
    manufacturer: 'Siemens Healthineers',
    serial: 'MEMAXV9W0',
    location: 'Unidad Móvil',
    status: 'Activo',
    installationDate: '2023-02-18',
    invima: 'INV-2021-11223',
    risk: 'IIb',
    imageUrl: 'https://picsum.photos/seed/EQP-017/600/400',
    imageZoom: 1,
    sede: 'Principal',
    accessories: [],
    predominantTechnologies: ['Eléctrica'],
    technicalParameters: {},
    supplies: [{ name: 'Electricidad', value: 'Batería' }],
    otherCharacteristics: [],
  },
  {
    id: 'EQP-018',
    name: 'Endoscopio Flexible',
    model: 'GIF-1TH190',
    manufacturer: 'Olympus',
    serial: 'GF1THW0X1',
    location: 'Gastroenterología',
    status: 'Activo',
    installationDate: '2022-11-05',
    invima: 'INV-2020-33445',
    risk: 'IIa',
    imageUrl: 'https://picsum.photos/seed/EQP-018/600/400',
    imageZoom: 1,
    sede: 'Secundaria',
    accessories: [],
    predominantTechnologies: ['Mecánica'],
    technicalParameters: {},
    supplies: [],
    otherCharacteristics: [],
  },
  {
    id: 'EQP-019',
    name: 'Analizador de Gases en Sangre',
    model: 'ABL90 FLEX PLUS',
    manufacturer: 'Radiometer',
    serial: 'ABL90X1Y2',
    location: 'Laboratorio de Urgencias',
    status: 'Activo',
    installationDate: '2023-06-30',
    invima: 'INV-2022-55667',
    risk: 'IIa',
    imageUrl: 'https://picsum.photos/seed/EQP-019/600/400',
    imageZoom: 1,
    sede: 'Terciaria',
    accessories: [],
    predominantTechnologies: ['Electrónica'],
    technicalParameters: {},
    supplies: [{ name: 'Electricidad', value: '110V' }],
    otherCharacteristics: [],
  },
  {
    id: 'EQP-020',
    name: 'Aspirador de Secreciones',
    model: 'Vacu-Aide QSU',
    manufacturer: 'DeVilbiss',
    serial: 'VAQSUY2Z3',
    location: 'Terapia Respiratoria',
    status: 'Activo',
    installationDate: '2021-10-25',
    invima: 'INV-2019-77889',
    risk: 'IIa',
    imageUrl: 'https://picsum.photos/seed/EQP-020/600/400',
    imageZoom: 1,
    sede: 'Principal',
    accessories: [],
    predominantTechnologies: ['Neumática'],
    technicalParameters: {},
    supplies: [
        { name: 'Electricidad', value: 'Batería' },
        { name: 'Vacío', value: 'Portátil' }
    ],
    otherCharacteristics: [],
  },
];
